changelog:
  exclude:
    authors:
      - renovate[bot]
    categories:
      - title: Features
        labels:
          - feature
      - title: Bug Fixes
        labels:
          - fix
      - title: Miscellaneous Chores
        labels:
          - chore
          - ci
          - docs
          - test
      - title: Other Changes
        labels:
          - "*"
